{ pkgs, pkgs-stable, ... }:
{
  home.packages = with pkgs; [
    ungoogled-chromium
    obs-studio
    adwsteamgtk
    fswatch
    nerd-fonts.jetbrains-mono
    alacritty
    xwayland-satellite
    fuzzel
    gh
    swaylock
    python3
    nautilus
    fastfetch
    htop
    osu-lazer-bin
    waybar
    supersonic
    prismlauncher
    zsh-powerlevel10k
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    zsh-history-substring-search
    zsh-fzf-tab
    fzf
    openjdk21
    yt-dlp
    exiftool
    id3v2
    steam
    bat
    httpie
    viu
    file
    macchanger
    tldr
    caligula
    ostui
    dwarf-fortress
    pokete
    netscanner
    yazi
    duf
    dust
    eza
    gitui
    mindustry-wayland
    godot
    pkgs-stable.azahar
    pkgs-stable.melonDS
    pkgs-stable.ryubing
    pkgs-stable.cemu
    pkgs-stable.mgba
  ];

}
